version: '3.8'

services:
  web:
    build: .
    ports:
      - "5501:5501"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    command: python app.py
